const defaultProducts = [
  {id:1,name:'Casa moderna en Tegucigalpa',type:'Propiedad',category:'Venta',price:245000,reservation:1500,status:'Activo',location:'Tegucigalpa, Honduras',image:'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',description:'Casa familiar con espacios abiertos, estacionamiento privado, área social y excelente ubicación para compradores que buscan seguridad y plusvalía.',attributes:['3 habitaciones','2.5 baños','220 m²','Parqueo privado']},
  {id:2,name:'Apartamento ejecutivo amueblado',type:'Propiedad',category:'Renta',price:950,reservation:300,status:'Activo',location:'San Pedro Sula, Honduras',image:'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80',description:'Apartamento listo para renta con diseño moderno, seguridad 24/7 y acceso rápido a zonas comerciales.',attributes:['2 habitaciones','2 baños','95 m²','Amueblado']},
  {id:3,name:'Terreno residencial premium',type:'Propiedad',category:'Venta',price:68000,reservation:800,status:'Activo',location:'Valle de Ángeles, Honduras',image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',description:'Terreno ideal para construcción residencial con clima agradable, acceso vehicular y alto potencial de crecimiento.',attributes:['900 m²','Acceso vial','Zona residencial','Documentación lista']},
  {id:4,name:'Asesoría legal inmobiliaria',type:'Servicio',category:'Servicios Legales',price:250,reservation:0,status:'Activo',location:'Servicio remoto/presencial',image:'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&w=1200&q=80',description:'Revisión de documentos, promesas de compra, contratos de arrendamiento y acompañamiento legal básico.',attributes:['Contrato','Revisión legal','Compra/venta','Renta']},
  {id:5,name:'Home makeover para venta',type:'Servicio',category:'Remodelación',price:1200,reservation:200,status:'Activo',location:'Tegucigalpa y alrededores',image:'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80',description:'Servicio de mejora visual para preparar una propiedad antes de publicarla, incluyendo pintura, decoración y ajustes de presentación.',attributes:['Pintura','Decoración','Reparaciones menores','Fotografía']},
  {id:6,name:'Fotografía inmobiliaria profesional',type:'Servicio',category:'Marketing',price:180,reservation:50,status:'Inactivo',location:'Honduras',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',description:'Sesión fotográfica para destacar propiedades en listados digitales y mejorar la conversión de interesados.',attributes:['20 fotos','Edición básica','Entrega digital','Optimización visual']}
];
function getProducts(){const saved=localStorage.getItem('products'); if(saved) return JSON.parse(saved); localStorage.setItem('products',JSON.stringify(defaultProducts)); return defaultProducts;}
function saveProducts(products){localStorage.setItem('products',JSON.stringify(products));}
function getCart(){return JSON.parse(localStorage.getItem('requestCart')||'[]');}
function saveCart(cart){localStorage.setItem('requestCart',JSON.stringify(cart));}
function formatMoney(n){return '$'+Number(n||0).toLocaleString('en-US');}
